[[redirects]]
  from = "/send"
  to = "https://shopanov.com/mycourse/netlify.toml"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"